### ISSUE TITLE
I would like to sort the foreign case-insensitive workspace folders

### ISSUE THREAD

**Issue by gusbemacbe** [iciclesoft/workspacesort-for-VSCode#12]
Hallo @iciclesoft !

See the screenshot:

![imagem](https://user-images.githubusercontent.com/2257024/115579236-56cff800-a29c-11eb-86b5-0c250cd72388.png)

It should be like: `aparecida, época, futuros, orçamentos, PUC`. 

In reference:

- https://stackoverflow.com/questions/8996963/how-to-perform-case-insensitive-sorting-in-javascript
- https://www.tutorialspoint.com/case-sensitive-sort-in-javascript (ideal and recommended)
- https://www.reddit.com/r/typescript/comments/7ishd1/need_help_with_case_insensitive_sort_of_an_array/

**Comment by iciclesoft** [comment]
Hi @gusbemacbe, sorry for the late reply but I have been very busy due to a move to a new home. To me, correctly sorting punctuations makes sense. I personally always found it rather odd to sort case sensitive, but that could just be me :) for now I will fix the correct sorting on the punctuation marks and leave the case insensitive sorting, also because the extension always worked like that.

**Comment by iciclesoft** [comment]
A new release has been published with the punctuation mark correction on sorting.

**Comment by gusbemacbe** [comment]
Dank u wel, wanneer ik huis ben, zal ik dat testen.
